show announcement dates (#35)
pachli/pachli-android pull request #151
Opened 2023-10-11 13:13 UTC by sanao1006

# Overview
Previously, it was inconvenient to know when "Announcements" were announced.
For example, when an announcement is made that "we will update tonight," it is inconvenient if the date of the announcement is not known.

Furthermore, it would be inconvenient if the update date was not displayed when the "Announcements" was updated
# Changes Made
- display the date when "Announcements" was published on the screen
    - supports relative and absolute time
-  display the date when "Announcements" is updated on the screen.

# Screenshot
**Before screenshot**
![image](https://github.com/pachli/pachli-android/assets/62137820/48092b78-6eac-4007-b8bc-a84bf0ef3305)

**The following  after screenshots**
relative time | absolute time
:--: | :--:
| ![image](https://github.com/pachli/pachli-android/assets/62137820/8eade16c-5148-4fa5-933d-79d8824f4166) |![image](https://github.com/pachli/pachli-android/assets/62137820/524b5992-8cb6-42d5-b308-b11e5c8646f9)

relative time with update time | absolute time with update time
:--: | :--:
| <image src="https://github.com/pachli/pachli-android/assets/62137820/fe556362-45d7-45aa-996e-1e44e7d1e19f" width="300" /> |<image src="https://github.com/pachli/pachli-android/assets/62137820/d1e82e29-1619-402b-bba0-1b5b84f8e426" width="300" />

## Concern
The "ago" at the end of the date may not be necessary. English speakers can probably understand the meaning without "ago" (just my opinion).This would also make the "ago" appear in the timeline date. 

But I have no hesitation in modifying it if you feel it is necessary!
# Related Issues
Fixes #35

2023-10-11 22:04 UTC, nikclayton requested changes
Thanks for the PR. Please let me know if any of the feedback isn't clear, or if you have more questions.

2023-10-11 22:04 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        val updatedAtText = if (item.updatedAt.toString() != item.publishedAt.toString()) {
Is the `.toString()` needed here? `updatedAt` and `publishedAt` are both `Date`, so should compare without needing this conversion?

Or is this about clamping them to midnight if `item.allDay` is true?

2023-10-11 22:04 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +            "(Updated: ${
Please create a string resource for this so it can be translated, instead of hardcoding an English string.

2023-10-11 22:04 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        val emojifiedText: CharSequence =
Please can you undo these formatting changes (and the other ones in this PR) that are unrelated to the actual change. Thanks.

2023-10-12 12:10 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        val updatedAtText = if (item.updatedAt.toString() != item.publishedAt.toString()) {
There is a reason for this.

Please see the following image. This is the behavior when `toString()` is removed.
![image](https://github.com/pachli/pachli-android/assets/62137820/abe412f7-ce76-4c28-b16d-e79a8ca025bb)
The updated date is shown even though publishedAT and updatedAt are the same. 

I have investigated the phenomenon of this behavior, and it seems that there is sometimes a slight time lag, even if there is no update (there are cases where there is no time lag).
![image](https://github.com/pachli/pachli-android/assets/62137820/ba455467-0cb1-43e5-9e2d-061b980f2cec)

When I added `toString()`, it behaved in a seemingly working way. But you are correct, this would not be a very good implementation.
How should I deal with this behavior?

2023-10-12 12:23 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +    private val preferences: SharedPreferences,
Thanks for the feedback!
> Please don't pass in SharedPreferences here. Instead, 

If you don't mind, may I ask you to tell me the reason for this? 
Is it simply because it would be bad for performance?

2023-10-12 12:33 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +    private val preferences: SharedPreferences,
Also, regarding `useAbsoluteTime`, 

am I correct in assuming that I pass `preferences.getBoolean(PrefKeys.ABSOLUTE_TIME_VIEW, false)` as the last argument in [this part](https://github.com/pachli/pachli-android/blob/ff5d7f1d27e98059e7eab1fa7acb1c1f59501da3/app/src/main/java/app/pachli/components/announcements/AnnouncementsActivity.kt#L105) ?

Like this.
```kotlin
adapter = AnnouncementAdapter(emptyList(), this, wellbeingEnabled, animateEmojis, preferences.getBoolean(PrefKeys.ABSOLUTE_TIME_VIEW, false))
```

2023-10-12 13:37 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        val updatedAtText = if (item.updatedAt.toString() != item.publishedAt.toString()) {
That's a great idea! Thanks for the response!

2023-10-12 14:13 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        val updatedAtText = if (item.updatedAt.toString() != item.publishedAt.toString()) {
> ```fun Date.equalByMinute(other: Date): Boolean {  ```

In which file should I put this function?
I plan to create a `DateExtensions.kt` in the `util` directory and put `Date.equalByMinute` there, what do you think?

2023-10-12 14:32 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +    private val preferences: SharedPreferences,
> Thanks for the feedback!
> 
> > Please don't pass in SharedPreferences here. Instead,
> 
> If you don't mind, may I ask you to tell me the reason for this? Is it simply because it would be bad for performance?

It's not a performance concern, it's a readability/understandability concern.

Generally (and the existing code is not always great about doing this) functions/methods should only take the data they need to operate as parameters.

When reading the code this can make it easier to reason about what's going on, and it limits what the function can do.

For example, by passing in the `SharedPreferences` object the adapter *could* modify the preferences. It doesn't, but to confirm that you have to look at the code.

It also makes testing easier. To test this adapter I only need to construct a small amount of fake data. But if it received a `SharedPreferences` object I'd need to create a fake one of those and make sure it behaves appropriately so that the tests work.

You can see an example of doing this in https://github.com/pachli/pachli-android/pull/143/files#diff-8295ab01e59c31c48e579546ab76c184e15c18d1f3c2f47d64abbea5094917b0

Before that PR the `ConversationsRemoteMediator` took `AppDatabase` as a parameter. But the code only needs two things:

1. Access to the `ConversationsDao`
2. Run multiple dao operations in a single database transaction

Those can be factored out in to two separate parameters, and now the `ConversationsRemoteMediator` can only interact with the parts of the database it's supposed to.

As I say, the existing code doesn't always do this very well, and this is also a judgement call -- if you've got an object with 10 properties and the method needs five of them, do you provide the object as a single parameter, or five parameters for each of the properties? There's not always a single right answer.

But in this case, where the code only needs a small number of values from the preferences, and it's going to write to them, passing them in as separate parameters is more appropriate.

2023-10-12 14:40 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +    private val preferences: SharedPreferences,
> Also, regarding `useAbsoluteTime`,
> 
> am I correct in assuming that I pass `preferences.getBoolean(PrefKeys.ABSOLUTE_TIME_VIEW, false)` as the last argument in [this part](https://github.com/pachli/pachli-android/blob/ff5d7f1d27e98059e7eab1fa7acb1c1f59501da3/app/src/main/java/app/pachli/components/announcements/AnnouncementsActivity.kt#L105) ?
> 
> Like this.
> 
> ```kotlin
> adapter = AnnouncementAdapter(emptyList(), this, wellbeingEnabled, animateEmojis, preferences.getBoolean(PrefKeys.ABSOLUTE_TIME_VIEW, false))
> ```

Sort of. But if you look at the current code immediately above it looks like this:

```kotlin
val preferences: SharedPreferences = PreferenceManager.getDefaultSharedPreferences(this)
val wellbeingEnabled = preferences.getBoolean(PrefKeys.WELLBEING_HIDE_STATS_POSTS, false)
val animateEmojis = preferences.getBoolean(PrefKeys.ANIMATE_CUSTOM_EMOJIS, false)

adapter = AnnouncementAdapter(emptyList(), this, wellbeingEnabled, animateEmojis)
```

Using different variables for the values helps make the code more readable, so you'd do:

Either:

```kotlin
val preferences: SharedPreferences = PreferenceManager.getDefaultSharedPreferences(this)
val wellbeingEnabled = preferences.getBoolean(PrefKeys.WELLBEING_HIDE_STATS_POSTS, false)
val animateEmojis = preferences.getBoolean(PrefKeys.ANIMATE_CUSTOM_EMOJIS, false)
val useAbsoluteTime = preferences.getBoolean(PrefKeys.ABSOLUTE_TIME_VIEW, false)  // <-- this is new

adapter = AnnouncementAdapter(emptyList(), this, wellbeingEnabled, animateEmojis, useAbsoluteTime)
```

Or -- because Kotlin supports named parameters, a slightly bigger change:

```kotlin
val preferences: SharedPreferences = PreferenceManager.getDefaultSharedPreferences(this)

adapter = AnnouncementAdapter(
    items = emptyList(),
    listener = this,
    wellbeingEnabled = preferences.getBoolean(PrefKeys.WELLBEING_HIDE_STATS_POSTS, false),
    animateEmojis = preferences.getBoolean(PrefKeys.ANIMATE_CUSTOM_EMOJIS, false),
    useAbsoluteTime = preferences.getBoolean(PrefKeys.ABSOLUTE_TIME_VIEW, false),
)
```

Either of those would be more readable.

2023-10-12 14:42 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        val updatedAtText = if (item.updatedAt.toString() != item.publishedAt.toString()) {
That would be fine.

2023-10-14 17:15 UTC, nikclayton commented
Hi @sanao1006 -- I see the new commits. Is this ready for another review, or do you still have changes you intend to make?

2023-10-14 21:47 UTC, sanao1006 commented
Oh, sorry.  I'm ready, please review.

2023-10-15 11:40 UTC, nikclayton requested changes
Thanks for the updates. Just one more thing I think, and then this is good to go.

Which server are you using that has announcements? None of the servers I have test accounts with are showing any announcements at the moment, so if you can recommend one I can create an account there to try this out.

When you're ready for me to review this again you can either add a comment that @-mentions me and I'll be notified, or click the arrows next to my name at the top right of the page (in the "Reviewers" section) -- that should also notify me to take a look.

Thanks for doing the work.

2023-10-15 11:40 UTC, nikclayton commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        holder.binding.announcementDate.text = "$publishTimeToDisplay $updatedAtText"
This should be from a resource string as well, so that translations can change the order that these appear, the same way you did `reaction_name_and_count`.

2023-10-16 00:41 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/announcements/AnnouncementAdapter.kt
> +        holder.binding.announcementDate.text = "$publishTimeToDisplay $updatedAtText"
> Thanks for the updates.

👍

> Which server are you using that has announcements?

I use the following servers to verify announcements
- fedibird.com (server for Japanese, but useful for date verification only)
- mastodon.world (useful for "updatedAt" verification)
- techhub.social

2023-10-16 18:04 UTC, nikclayton approved these changes
LGTM. Thanks a lot.

2023-10-16 18:04 UTC, merged