feat: Implementation of feature to hide self-boosts (#39)
pachli/pachli-android pull request #193
Opened 2023-10-22 04:37 UTC by sanao1006

# Overview
Some Mastodon posters have a annoying habit of boosting their own posts some time after they've posted them. 
Some people got fed up , TL became disorganized due to this.

No need to see the same toot over and over again.

# Changes Made
- Add an additional option to the "Filters > Tabs" preference to show these self-boosts (default: on)

# Screenshot
***screen of "Filters > Tabs" preference***
before | after
:--: | :--:
| ![image](https://github.com/pachli/pachli-android/assets/62137820/e34e4620-3852-4f46-9663-bf1046f35e5f) |![image](https://github.com/pachli/pachli-android/assets/62137820/6d462fce-b746-4aeb-8c29-c7c5f157efb9)

***screen of Home Timeline***
***switch-on(self-boosts are displayed)*** | ***swith-off(self-boosts are not displayed)***
:--: | :--:
| ![image](https://github.com/pachli/pachli-android/assets/62137820/765fb73a-462a-4cae-a1d3-5817a10ec07d) |![image](https://github.com/pachli/pachli-android/assets/62137820/cacd5c40-dbbf-490c-a65c-b503d2936af2)

# Concern
With the current implementation, when "Show boosts" is OFF, boosts are not displayed whether "Show self-boosts" is ON or OFF. Is this behavior OK?

# Related issue
Fixes #39

2023-10-22 05:05 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +            ((status.reblog != null && status.account.username == statusViewData.username) && filterRemoveSelfReblogs)
username is used to determine if the person who tooted and the person who tooted the boosted toot are the same. For example
```kotlin
@sanao1006@mastodon.social == @sanao1006@mastodon.social
// → true
```

However, this approach seems a bit un-smart. Any other good ideas (e.g., using id)?

2023-10-22 13:35 UTC, nikclayton requested changes
Thanks for contributing this. I've attached some suggestions.

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/preference/TabFilterPreferencesFragment.kt
> +                }
Untested, but if you put

```kotlin
dependency = PrefKeys.TAB_FILTER_HOME_BOOSTS
```

here then the new preference should be disabled when the "show boosts" preference is disabled (see the description in https://developer.android.com/develop/ui/views/components/settings/components-and-attributes).

This should make it clear to the user that if they disabled all boosts then the "disable self boosts" setting is ignored.

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +            ((status.reblog != null && status.account.username == statusViewData.username) && filterRemoveSelfReblogs)
Yes, you're right, that could be a problem, because `username` doesn't include the domain (https://docs.joinmastodon.org/entities/Account/#username) so if user `@foo@server1.example` reblogs a post from `@foo@server2.example` this code would consider that to be a self-boost, because the `username` parts are the same.

As you say, it would be better to use `id` here.

Something like:

```kotlin
(filterRemoveSelfReblogs && (status.account.id == status.reblog?.account?.id))
```

should do it (untested).

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/settings/SettingsConstants.kt
> +    const val TAB_FILTER_HOME_SELF_BOOSTS = "tabFilterHomeSelfBoosts"
```suggestion
    const val TAB_SHOW_HOME_SELF_BOOSTS = "tabShowHomeSelfBoosts"
```

Per earlier comment.

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +            PrefKeys.TAB_FILTER_HOME_SELF_BOOSTS -> {
```suggestion
            PrefKeys.TAB_SHOW_HOME_SELF_BOOSTS -> {
```

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +                val filter = sharedPreferencesRepository.getBoolean(PrefKeys.TAB_FILTER_HOME_SELF_BOOSTS, true)
```suggestion
                val filter = sharedPreferencesRepository.getBoolean(PrefKeys.TAB_SHOW_HOME_SELF_BOOSTS, true)
```

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +                !sharedPreferencesRepository.getBoolean(PrefKeys.TAB_FILTER_HOME_SELF_BOOSTS, true)
```suggestion
                !sharedPreferencesRepository.getBoolean(PrefKeys.TAB_SHOW_HOME_SELF_BOOSTS, true)
```

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +            PrefKeys.TAB_FILTER_HOME_SELF_BOOSTS -> {
Per earlier suggestion.

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/components/timeline/viewmodel/TimelineViewModel.kt
> +                val filter = sharedPreferencesRepository.getBoolean(PrefKeys.TAB_FILTER_HOME_SELF_BOOSTS, true)
Per earlier suggestion.

2023-10-22 13:35 UTC, nikclayton commented on app/src/main/java/app/pachli/settings/SettingsConstants.kt
> +    const val TAB_FILTER_HOME_SELF_BOOSTS = "tabFilterHomeSelfBoosts"
Per earlier suggestion.

2023-10-23 12:58 UTC, sanao1006 commented
Behavior of the switchPreference
<video src="https://github.com/pachli/pachli-android/assets/62137820/d268d2d8-3ec8-4059-9113-5aa128115273" />

2023-10-23 13:04 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/preference/TabFilterPreferencesFragment.kt
> +                }.apply { dependency = PrefKeys.TAB_FILTER_HOME_BOOSTS }
```kotlin
  ...
  setDefaultValue(true)
  isIconSpaceReserved = false
  dependency = PrefKeys.TAB_FILTER_HOME_BOOSTS
}
```
I really wanted to write the above code, but the following error occurred.
```
java.lang.IllegalStateException: Dependency "tabFilterHomeBoosts" not found for preference "tabShowHomeSelfBoosts" (title: "Show self-boosts"
```
I couldn't figure out how to solve this error and tried various ways, but when I used `apply`, it worked. So, I am sorry, but I have no evidence as to why it worked when I used `apply`...

2023-10-23 20:43 UTC, nikclayton approved these changes
Looks good, thanks. I'll release a version of Pachli Current with this in the next hour or so, and this will be in 1.3 which I aim to have released on Wednesday.

2023-10-23 20:43 UTC, nikclayton commented on app/src/main/java/app/pachli/components/preference/TabFilterPreferencesFragment.kt
> +                }.apply { dependency = PrefKeys.TAB_FILTER_HOME_BOOSTS }
Huh. That'll be something in the way SettingsDSL manages things. Not to worry, this is absolutely fine.

2023-10-23 20:47 UTC, merged

2023-10-23 22:03 UTC, sanao1006 commented
Thanks for your review!