refactor: replace `androidx.appcompat.widget.toolbar` with `com.google.android.material.appbar.material toolbar`(#28)
pachli/pachli-android pull request #212
Opened 2023-11-03 08:17 UTC by sanao1006

# Overview
The previous code used `androidx.appcompat.widget.Toolbar` in a several places.
However, the pachli project intends to adopt `com.google.android.material.appbar.MaterialToolbar` as the Toolbar layout.

In addition, it is necessary to prevent future code writers or reviewers from inadvertently merging `androidx.appcompat.widget.Toolbar` into the project.
# Changes made
- Create a custom lint rule that finds `androidx.appcompat.widget.Toolbar` in the code and warns to use `com.google.android.material.appbar.MaterialToolbar` instead
    - This is because there's a high possibility that a writer could inadvertently write this or that a reviewer could miss it.
 
- Create tests to verify that the custom lint rules work properly 

- Replace all `androidx.appcompat.widget.Toolbar` in the project with `com.google.android.material.appbar.MaterialToolbar`

# Screenshot
Before(No warning) | After(Waning displayed)
:--: | :--:
|![image](https://github.com/pachli/pachli-android/assets/62137820/345bc0d5-f4c2-4815-a0aa-6cbb6edbb556)|![image](https://github.com/pachli/pachli-android/assets/62137820/ba05d054-d21f-42a9-b1ab-f54afa39cfa8)

# Related issue
Fixes #28

2023-11-03 08:45 UTC, sanao1006 commented on checks/src/test/java/app/pachli/lint/checks/AndroidxToolbarDetectorTest.kt
> +class AndroidxToolbarDetectorTest {
I want to run this test class with ci, but `. /gradlew app:testOrangeDebugUnitTest ` doesn't seem to run with it.
Perhaps the code in `.github/workflows/ci.yml` could be changed to `run: . /gradlew app:testOrangeDebugUnitTest checks:test` might work, but any other suggestions?

2023-11-04 21:10 UTC, nikclayton commented on checks/src/test/java/app/pachli/lint/checks/AndroidxToolbarDetectorTest.kt
> +class AndroidxToolbarDetectorTest {
That's probably the easiest fix at the moment. Please can you add that to this PR.

I'm working on a change that splits the project up in to additional modules with common configuration for flavors that will fix this, but it's not ready yet.

2023-11-04 21:12 UTC, nikclayton commented on checks/src/test/java/app/pachli/lint/checks/AndroidxToolbarDetectorTest.kt
> +        """,
```suggestion
                """res/layout/test.xml:16: Warning: Use com.google.android.material.appbar.MaterialToolbar instead of androidx.appcompat.widget.Toolbar [AndroidxToolbarDetector]
                        <androidx.appcompat.widget.Toolbar
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0 errors, 1 warnings
        """,
```

2023-11-04 21:15 UTC, nikclayton requested changes
Looks very good, thanks.

I made one change via the GH UI -- I modified AndroidToolbarDetector.kt to include a suggested fix in the report, that way it's fixable with Alt-Enter in Android Studio. This changed the test output slightly so I modified that as well.

Apart from that, this is just about ready to go. If you can make that change to the CI YAML file as well to run the tests then this can get merged.

Thanks again.

2023-11-05 09:26 UTC, sanao1006 commented
I have fixed it.
Please review!

2023-11-05 12:39 UTC, nikclayton approved these changes

2023-11-05 12:51 UTC, merged

2023-11-05 12:52 UTC, nikclayton commented
Good, and merged. Thanks again -- this will make future code cleanups easier, because the framework to write a lint check to catch the problem is now in place.

2023-11-05 12:55 UTC, sanao1006 commented
Sounds good! Thanks for yor review!