feat: Display compose button when viewing hashtags
pachli/pachli-android pull request #254
Opened 2023-11-15 07:00 UTC by sanao1006

# Overview
The previous code didn't display the compose button when viewing hashtags, which was inconvenient.

Therefore, display the button when viewing hashtags.

# Changes
- display the button when viewing hashtags.
- insert the hashtag in the draft message when clicking the button

# Video

https://github.com/pachli/pachli-android/assets/62137820/49de569f-2296-4a46-857f-43b47b1fa898

https://github.com/pachli/pachli-android/assets/62137820/8ce40dd3-0da4-47d9-a18f-1f09ea6723c3

# Concern
- I didn't know how `actionButtonPresent()` should be implemented. It seems to be working fine, but maybe I should implement

# Related issue
Fixes #228

2023-11-15 07:15 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
> +        if (intent.getStringExtra(HASHTAG) == null) {
I did not know how to insert the hashtag received using intent into `composeEditField`, so I may have implemented it incorrectly.

2023-11-15 15:54 UTC, nikclayton commented on app/src/main/java/app/pachli/StatusListActivity.kt
> +        }
I think there's a cleaner way to do this.

At the moment what happens with a "compose" is controlled by a `ComposeOptions` class. This is created and populated, then passed in the intent to `ComposeActivity`. Then `ComposeActivity` hands this off to `ComposeViewModel` which sets things up.

[It's not the cleanest bit of code, but fixing some of its issues is outside the scope of this]

`ComposeActivity` has a static `startIntent()` method you can call which takes the options, sets everything up, and returns an intent you can use.

So (untested), you can do something like this here I think:

```kotlin
val composeIntent = when (timelineKind) {
    if TimelineKind.Tag -> {
        val tag = timelineKind.tags.first()
        ComposeActivity.startIntent(
            this,
            ComposeOptions(content = getString(R.string.title_tag).format(hashtag)),
        )
    }
    else -> null
}

if (composeIntent == null) {
    binding.composeButton.hide()
} else {
    binding.composeButton.setOnClickListener { startActivity(composeIntent) }
    binding.composeButton.show()
}
```

This will get the correct intent, and hide/show the FAB depending on whether or not there is an intent.

Then you don't need the changes to `ComposeActivity` or `strings.xml`.

Creating the compose intent for the other list types can then be done by extending the `is ...` clauses in the `when` block.

Does that make sense?

2023-11-15 23:43 UTC, sanao1006 commented on app/src/main/java/app/pachli/StatusListActivity.kt
> +        }
Thank you for your kind review!
> Does that make sense?

Yes, I understand.

Sorry, I lacked understanding of `ComposeActivity`. I'll try harder!

2023-11-16 09:15 UTC, nikclayton commented on app/src/main/java/app/pachli/StatusListActivity.kt
> +        }
No problem at all. There is quite a lot of code to go through at the moment to understand how everything works.

2023-11-16 15:39 UTC, nikclayton commented
That's looking great, thanks.

I've been trying this out, and one thing that occurred to me is -- where should the cursor be when the user first creates the post?

At the moment it's placed at the end of the hashtag, and there's no space between the cursor and the tag. So the user is either going to have to insert a space every time, or manually move the cursor back to the start of the tag if they want the tag to be at the end of the post.

I suspect it would be better if the cursor was at the start of the post, and there was a space between the cursor and the tag, because I think (and this is just a guess) most people would want to put the tags at the end.

So if `|` represents the cursor, currently it's:

```
#hashtag|
```

but it should be:

```
| #hashtag
```

Then the user can immediately start typing, and the tag will appear at the end of their post.

What do you think?

If you agree, I'd do this by (untested):

1. Creating an enum to represent the initial cursor position;

```kotlin
enum class InitialCursorPosition {
    START,
    END,
}
```

2. Add the cursor position as a field to `ComposeOptions`, with a default of `END` to keep the current behaviour.

3. Set the cursor position in the compose options for a hashtag to `START`.

4. Add a space immediately before the hashtag in the compose options content.

5. Set the cursor position in `ComposeActivity.onCreate()`, probably immediately after this code, `binding.composeEditField.setText(statusContent)`

It's a bit more work, but it might be a nicer user experience. How do you feel about that?

2023-11-17 04:39 UTC, sanao1006 commented
I largely agree!

> Add the cursor position as a field to ComposeOptions, with a default of END to keep the current behaviour.

Does this mean that by default the cursor position is like  `#hashtag |`?

That is just my feeling, but by default, the cursor position is more comfortable with `START` (e.g. `| #hashtag`.).
However, this may be a difference in cultural sensibilities, so I respect Nick's opinion (Because Mastodon has many English-speaking users)!

2023-11-17 08:15 UTC, sanao1006 commented
Oh, sorry, I may have misunderstood.

I mistakenly thought you were going to allow the users to set the cursor's initial position at `START`(e.g. `| #hashtag`) and `END` (e.g. `#hashtag |`)
And I was wondering if you were suggesting that the initial position be `END` (e.g. `#hashtag |`).


You simply suggested setting the `initialCursorPosition` to be added to `ComposeOptions` with an initial value of `END` as follows
```kotlin
        ...
        var statusId: String? = null,.
        var kind: ComposeKind? = null,.
        var initialCursorPosition: InitialCursorPosition = InitialCursorPosition.END
    ) : Parcelable
```
And you intended to set the initial value of `StatusListActivity` to `START` as follows, right?
```kotlin
ComposeActivity.startIntent(
   this,
   ComposeActivity.ComposeOptions(
       content = getString(R.string.title_tag).format(tag),
       initialCursorPosition = ComposeActivity.InitialCursorPosition.START,
),
```
(And then insert a space after this)

But, This interpretation may also be incorrect, so I would like to reconcile the perceptions between you and me!

2023-11-17 10:14 UTC, nikclayton commented
> Oh, sorry, I may have misunderstood.
> 
> I mistakenly thought you were going to allow the users to set the cursor's initial position at `START`(e.g. `| #hashtag`) and `END` (e.g. `#hashtag |`) And I was wondering if you were suggesting that the initial position be `END` (e.g. `#hashtag |`).
> 
> You simply suggested setting the `initialCursorPosition` to be added to `ComposeOptions` with an initial value of `END` as follows
> 
> ```kotlin
>         ...
>         var statusId: String? = null,.
>         var kind: ComposeKind? = null,.
>         var initialCursorPosition: InitialCursorPosition = InitialCursorPosition.END
>     ) : Parcelable
> ```
> 
> And you intended to set the initial value of `StatusListActivity` to `START` as follows, right?
> 
> ```kotlin
> ComposeActivity.startIntent(
>    this,
>    ComposeActivity.ComposeOptions(
>        content = getString(R.string.title_tag).format(tag),
>        initialCursorPosition = ComposeActivity.InitialCursorPosition.START,
> ),
> ```
> 
> (And then insert a space after this)
> 
> But, This interpretation may also be incorrect, so I would like to reconcile the perceptions between you and me!

Yes, that's right.

So the default behaviour when creating a post is that the cursor is at the end, *except* when creating a post from a hashtag, where the cursor is at the start.

In that last example I think you can just embed the space directly in `content`, so it would be:

```kotlin
ComposeActivity.startIntent(
   this,
   ComposeActivity.ComposeOptions(
       content = " ${getString(R.string.title_tag).format(tag)}",
       initialCursorPosition = ComposeActivity.InitialCursorPosition.START,
),
```

(or, instead of reusing R.string.title_tag, create a new string resource just for this use that contains the embedded space in the right place).

2023-11-18 14:04 UTC, nikclayton requested changes

2023-11-18 14:04 UTC, nikclayton commented on app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
> +        binding.composeEditField.setSelection(0)
This isn't quite right, because it always places the cursor at the start. You can see this if you try and reply to a post -- previously you'd get a reply that starts with the addresses of the people being replied to, and then the cursor at the end.

Now you get the list of people being replied to and the cursor is at the start.

If you check the existing code you'll see there's a function called `setupComposeField()` which does this. At the moment it has a line:

```kotlin
binding.composeEditField.setSelection(binding.composeEditField.length())
```

which puts the cursor at the end, but your code here overrides that.

So what I think you need to do is:

1. Remove this line here
2. Add a `composeOptions: ComposeOptions?` parameter to `setupComposeField()`.
3. Pass this parameter when `setupComposeField()` is called (around line 260)

Then you can replace the 

```kotlin
binding.composeEditField.setSelection(binding.composeEditField.length())
```

in `setupComposeField()` with something like:

```kotlin
when (composeOptions?.initialCursorPosition ?: InitialCursorPosition.END) {
    InitialCursorPosition.START -> binding.composeEditField.setSelection(0)
    InitialCursorPosition.END -> binding.composeEditField.setSelection(
        binding.composeEditField.length()
    )
}
```

That way the `initialCursorPosition` value is honoured when the compose field is set up, and the default value is `END` which matches the current behaviour.

Does that make sense?

2023-11-19 07:34 UTC, sanao1006 commented on app/src/main/java/app/pachli/components/compose/ComposeActivity.kt
> +        binding.composeEditField.setSelection(0)
> Does that make sense?

Yes, I understand.

Sorry, I did not take replies into consideration.
It is indeed inconvenient because the current code makes the cursor go to the `START` position  in reply.

Thank you for pointing this out!

2023-11-19 08:47 UTC, sanao1006 commented
### Behavior
reply | hashtag |
:--: | :--:
| <video src="https://github.com/pachli/pachli-android/assets/62137820/c63999d1-c26e-4bc6-83b3-5c6b17303b4f" /> |<video src="https://github.com/pachli/pachli-android/assets/62137820/ccff3b78-48d5-40d6-a974-e091213bac41" /> |

2023-11-20 18:16 UTC, nikclayton approved these changes

2023-11-20 18:19 UTC, merged